title: Normannator - Homepage
email: contact@normannator.de
description: >-
  Welcome to the Homepage of Normannator, containing awesome ArchLinux Tutorials
  and other Tech-Content.
baseurl: ''
url: ''
twitter_username: ''
github_username: normannator
theme: minima
plugins:
  - jekyll-feed
